if getActivatedMods():contains("ItemTweakerAPI") then
require("ItemTweaker_Core");
else return end

--Food
--Canned Food
TweakItem("Base.Dogfood","DisplayCategory","FoCf");
TweakItem("Base.DogfoodOpen","DisplayCategory","FoCf");
TweakItem("Base.CannedBolognese","DisplayCategory","FoCf");
TweakItem("Base.CannedBologneseOpen","DisplayCategory","FoCf");
TweakItem("Base.CannedCarrots","DisplayCategory","FoCf");
TweakItem("Base.CannedCarrotsOpen","DisplayCategory","FoCf");
TweakItem("Base.CannedChili","DisplayCategory","FoCf");
TweakItem("Base.CannedCorn","DisplayCategory","FoCf");
TweakItem("Base.CannedCornedBeef","DisplayCategory","FoCf");
TweakItem("Base.CannedMushroomSoup","DisplayCategory","FoCf");
TweakItem("Base.CannedPeas","DisplayCategory","FoCf");
TweakItem("Base.CannedPotato2","DisplayCategory","FoCf");
TweakItem("Base.CannedSardines","DisplayCategory","FoCf");
TweakItem("Base.CannedTomato2","DisplayCategory","FoCf");
TweakItem("Base.TinnedBeans","DisplayCategory","FoCf");
TweakItem("Base.TinnedSoup","DisplayCategory","FoCf");
TweakItem("Base.TunaTin","DisplayCategory","FoCf");
TweakItem("Base.CannedChiliOpen","DisplayCategory","FoCf");
TweakItem("Base.CannedCornedBeefOpen","DisplayCategory","FoCf");
TweakItem("Base.CannedCornOpen","DisplayCategory","FoCf");
TweakItem("Base.CannedMushroomSoupOpen","DisplayCategory","FoCf");
TweakItem("Base.CannedPeasOpen","DisplayCategory","FoCf");
TweakItem("Base.CannedPotatoOpen","DisplayCategory","FoCf");
TweakItem("Base.CannedSardinesOpen","DisplayCategory","FoCf");
TweakItem("Base.CannedTomatoOpen","DisplayCategory","FoCf");
TweakItem("Base.OpenBeans","DisplayCategory","FoCf");
TweakItem("Base.TinnedSoupOpen","DisplayCategory","FoCf");
TweakItem("Base.TunaTinOpen","DisplayCategory","FoCf");

--Pickled Food
TweakItem("Base.CannedBellPepper","DisplayCategory","FoPf");
TweakItem("Base.CannedBroccoli","DisplayCategory","FoPf");
TweakItem("Base.CannedCabbage","DisplayCategory","FoPf");
TweakItem("Base.CannedCarrots2","DisplayCategory","FoPf");
TweakItem("Base.CannedEggplant","DisplayCategory","FoPf");
TweakItem("Base.CannedLeek","DisplayCategory","FoPf");
TweakItem("Base.CannedTomato","DisplayCategory","FoPf");
TweakItem("Base.CannedPotato","DisplayCategory","FoPf");
TweakItem("Base.CannedRedRadish","DisplayCategory","FoPf");

--Cooking
--Completed Meal
TweakItem("Base.PotOfSoup","DisplayCategory","FoCoCm");
TweakItem("Base.Oatmeal","DisplayCategory","FoCoCm");
TweakItem("Base.SoupBowl","DisplayCategory","FoCoCm");
TweakItem("Base.StewBowl","DisplayCategory","FoCoCm");
TweakItem("Base.RiceBowl","DisplayCategory","FoCoCm");
TweakItem("Base.PastaBowl","DisplayCategory","FoCoCm");
TweakItem("Base.BeanBowl","DisplayCategory","FoCoCm");
TweakItem("Base.CerealBowl","DisplayCategory","FoCoCm");

--Preparation
TweakItem("Base.PiePrep","DisplayCategory","FoCoPr");
TweakItem("Base.PieDough","DisplayCategory","FoCoPr");
TweakItem("Base.CakePrep","DisplayCategory","FoCoPr");
TweakItem("Base.CakeBatter","DisplayCategory","FoCoPr");
TweakItem("Base.BreadDough","DisplayCategory","FoCoPr");

--Evolved Recipe
TweakItem("Base.GriddlePanFriedVegetables","DisplayCategory","FoCoEr");
TweakItem("Base.PanFriedVegetables2","DisplayCategory","FoCoEr");
TweakItem("Base.PanFriedVegetables","DisplayCategory","FoCoEr");
TweakItem("Base.Sandwich","DisplayCategory","FoCoEr");
TweakItem("farming.Salad","DisplayCategory","FoCoEr");
TweakItem("Base.FruitSalad","DisplayCategory","FoCoEr");
TweakItem("Base.RicePan","DisplayCategory","FoCoEr");
TweakItem("Base.RicePot","DisplayCategory","FoCoEr");
TweakItem("Base.PotOfStew","DisplayCategory","FoCoEr");
TweakItem("Base.PotOfSoupRecipe","DisplayCategory","FoCoEr");
TweakItem("Base.PieWholeRaw","DisplayCategory","FoCoEr");
TweakItem("Base.PastaPan","DisplayCategory","FoCoEr");
TweakItem("Base.PastaPot","DisplayCategory","FoCoEr");
TweakItem("Base.HotDrink","DisplayCategory","FoCoEr");
TweakItem("Base.CakeRaw","DisplayCategory","FoCoEr");
TweakItem("Base.BurgerRecipe","DisplayCategory","FoCoEr");

--Spice
TweakItem("Base.Wasabi","DisplayCategory","FoCoSp");
TweakItem("Base.OilVegetable","DisplayCategory","FoCoSp");
TweakItem("Base.Soysauce","DisplayCategory","FoCoSp");
TweakItem("Base.Salt","DisplayCategory","FoCoSp");
TweakItem("Base.Pepper","DisplayCategory","FoCoSp");
TweakItem("Base.RiceVinegar","DisplayCategory","FoCoSp");
TweakItem("Base.OilOlive","DisplayCategory","FoCoSp");
TweakItem("Base.Mustard","DisplayCategory","FoCoSp");
TweakItem("farming.MayonnaiseFull","DisplayCategory","FoCoSp");
TweakItem("farming.MayonnaiseHalf","DisplayCategory","FoCoSp");
TweakItem("Base.Marinara","DisplayCategory","FoCoSp");
TweakItem("Base.MapleSyrup","DisplayCategory","FoCoSp");
TweakItem("Base.Ketchup","DisplayCategory","FoCoSp");
TweakItem("Base.Hotsauce","DisplayCategory","FoCoSp");
TweakItem("Base.Pepper","DisplayCategory","FoCoSp");

--Drink
TweakItem("Base.Wine","DisplayCategory","FoDr");
TweakItem("Base.Wine2","DisplayCategory","FoDr");
TweakItem("Base.WhiskeyFull","DisplayCategory","FoDr");
TweakItem("Base.Pop","DisplayCategory","FoDr");
TweakItem("Base.Pop2","DisplayCategory","FoDr");
TweakItem("Base.Pop3","DisplayCategory","FoDr");
TweakItem("Base.PopBottle","DisplayCategory","FoDr");
TweakItem("Base.Milk","DisplayCategory","FoDr");
TweakItem("Base.JuiceBox","DisplayCategory","FoDr");
TweakItem("Base.ColdCuppa","DisplayCategory","FoDr");
TweakItem("Base.BeerBottle","DisplayCategory","FoDr");
TweakItem("Base.BeerCan","DisplayCategory","FoDr");

--Refillable
TweakItem("farming.WateredCanFull","DisplayCategory","FoRe");
TweakItem("farming.RemouladeWaterFull","DisplayCategory","FoRe");
TweakItem("farming.MayonnaiseWaterFull","DisplayCategory","FoRe");
TweakItem("farming.GardeningSprayFull","DisplayCategory","FoRe");
TweakItem("Base.WineWaterFull","DisplayCategory","FoRe");
TweakItem("Base.WhiskeyWaterFull","DisplayCategory","FoRe");
TweakItem("Base.WaterSaucepan","DisplayCategory","FoRe");
TweakItem("Base.WaterPot","DisplayCategory","FoRe");
TweakItem("Base.WaterPopBottle","DisplayCategory","FoRe");
TweakItem("Base.WaterBowl","DisplayCategory","FoRe");
TweakItem("Base.WaterMug","DisplayCategory","FoRe");
TweakItem("Base.WaterBottleFull","DisplayCategory","FoRe");
TweakItem("Base.WaterBleachBottle","DisplayCategory","FoRe");
TweakItem("Base.FullKettle","DisplayCategory","FoRe");
TweakItem("Base.BucketWaterFull","DisplayCategory","FoRe");

--Protein
TweakItem("Base.Tofu","DisplayCategory","FoPr");
TweakItem("Base.Steak","DisplayCategory","FoPr");
TweakItem("Base.PorkChop","DisplayCategory","FoPr");
TweakItem("Base.MuttonChop","DisplayCategory","FoPr");
TweakItem("Base.MeatPatty","DisplayCategory","FoPr");
TweakItem("Base.HamSlice","DisplayCategory","FoPr");
TweakItem("Base.Ham","DisplayCategory","FoPr");
TweakItem("Base.FrogMeat","DisplayCategory","FoPr");
TweakItem("Base.EggCarton","DisplayCategory","FoPr");
TweakItem("Base.Egg","DisplayCategory","FoPr");
TweakItem("Base.Chicken","DisplayCategory","FoPr");
TweakItem("Base.BeefJerky","DisplayCategory","FoPr");
TweakItem("farming.BaconRashers","DisplayCategory","FoPr");
TweakItem("farming.BaconBits","DisplayCategory","FoPr");
TweakItem("farming.Bacon","DisplayCategory","FoPr");

--Game
TweakItem("Base.Smallanimalmeat","DisplayCategory","FoPrGa");
TweakItem("Base.Smallbirdmeat","DisplayCategory","FoPrGa");
TweakItem("Base.Rabbitmeat","DisplayCategory","FoPrGa");
TweakItem("Base.DeadBird","DisplayCategory","FoPrGa");
TweakItem("Base.DeadMouse","DisplayCategory","FoPrGa");
TweakItem("Base.DeadRabbit","DisplayCategory","FoPrGa");
TweakItem("Base.DeadRat","DisplayCategory","FoPrGa");
TweakItem("Base.DeadSquirrel","DisplayCategory","FoPrGa");

--Fish
TweakItem("Base.Trout","DisplayCategory","FoPrFi");
TweakItem("Base.Panfish","DisplayCategory","FoPrFi");
TweakItem("Base.Salmon","DisplayCategory","FoPrFi");
TweakItem("Base.Pike","DisplayCategory","FoPrFi");
TweakItem("Base.Perch","DisplayCategory","FoPrFi");
TweakItem("Base.BaitFish","DisplayCategory","FoPrFi");
TweakItem("Base.FishFillet","DisplayCategory","FoPrFi");
TweakItem("Base.Crappie","DisplayCategory","FoPrFi");
TweakItem("Base.Catfish","DisplayCategory","FoPrFi");
TweakItem("Base.Bass","DisplayCategory","FoPrFi");

--Forage
TweakItem("Base.Worm","DisplayCategory","FoFo");
TweakItem("Base.WildEggs","DisplayCategory","FoFo");
TweakItem("Base.Violets","DisplayCategory","FoFo");
TweakItem("Base.Rosehips","DisplayCategory","FoFo");
TweakItem("Base.LemonGrass","DisplayCategory","FoFo");
TweakItem("Base.Grasshopper","DisplayCategory","FoFo");
TweakItem("Base.GrapeLeaves","DisplayCategory","FoFo");
TweakItem("Base.Ginseng","DisplayCategory","FoFo");
TweakItem("Base.Cricket","DisplayCategory","FoFo");
TweakItem("Base.CommonMallow","DisplayCategory","FoFo");
TweakItem("Base.Cockroach","DisplayCategory","FoFo");
TweakItem("Base.BlackSage","DisplayCategory","FoFo");

--Fruit
TweakItem("Base.Watermelon","DisplayCategory","FoFr");
TweakItem("Base.WatermelonSliced","DisplayCategory","FoFr");
TweakItem("Base.WatermelonSmashed","DisplayCategory","FoFr");
TweakItem("farming.Strewberrie","DisplayCategory","FoFr");
TweakItem("Base.Pineapple","DisplayCategory","FoFr");
TweakItem("Base.Peach","DisplayCategory","FoFr");
TweakItem("Base.Orange","DisplayCategory","FoFr");
TweakItem("Base.Lime","DisplayCategory","FoFr");
TweakItem("Base.Lemon","DisplayCategory","FoFr");
TweakItem("Base.Grapes","DisplayCategory","FoFr");
TweakItem("Base.Cherry","DisplayCategory","FoFr");
TweakItem("Base.BerryBlack","DisplayCategory","FoFr");
TweakItem("Base.BerryBlue","DisplayCategory","FoFr");
TweakItem("Base.BerryGeneric1","DisplayCategory","FoFr");
TweakItem("Base.BerryGeneric2","DisplayCategory","FoFr");
TweakItem("Base.BerryGeneric3","DisplayCategory","FoFr");
TweakItem("Base.BerryGeneric4","DisplayCategory","FoFr");
TweakItem("Base.BerryGeneric5","DisplayCategory","FoFr");
TweakItem("Base.BerryPoisonIvy","DisplayCategory","FoFr");
TweakItem("Base.Apple","DisplayCategory","FoFr");
TweakItem("Base.Banana","DisplayCategory","FoFr");

--Grains
TweakItem("Base.Rice","DisplayCategory","FoGr");
TweakItem("Base.Flour","DisplayCategory","FoGr");
TweakItem("Base.Ramen","DisplayCategory","FoGr");
TweakItem("Base.Pasta","DisplayCategory","FoGr");
TweakItem("Base.Popcorn","DisplayCategory","FoGr");
TweakItem("Base.OatsRaw","DisplayCategory","FoGr");
TweakItem("Base.Bread","DisplayCategory","FoGr");
TweakItem("Base.BreadSlices","DisplayCategory","FoGr");

--Miscellaneous
TweakItem("Base.Yoghurt","DisplayCategory","FoMi");
TweakItem("Base.Yeast","DisplayCategory","FoMi");
TweakItem("Base.Waffles","DisplayCategory","FoMi");
TweakItem("Base.Vinegar","DisplayCategory","FoMi");
TweakItem("Base.TVDinner","DisplayCategory","FoMi");
TweakItem("Base.Teabag2","DisplayCategory","FoMi");
TweakItem("Base.SunflowerSeeds","DisplayCategory","FoMi");
TweakItem("Base.Sugar","DisplayCategory","FoMi");
TweakItem("Base.Pie","DisplayCategory","FoMi");
TweakItem("Base.PiePumpkin","DisplayCategory","FoMi");
TweakItem("Base.Pizza","DisplayCategory","FoMi");
TweakItem("Base.Processedcheese","DisplayCategory","FoMi");
TweakItem("Base.Peanuts","DisplayCategory","FoMi");
TweakItem("Base.PeanutButter","DisplayCategory","FoMi");
TweakItem("Base.Pancakes","DisplayCategory","FoMi");
TweakItem("Base.PeanutButterSandwich","DisplayCategory","FoMi");
TweakItem("Base.MintCandy","DisplayCategory","FoMi");
TweakItem("Base.Modjeska","DisplayCategory","FoMi");
TweakItem("Base.MeatDumpling","DisplayCategory","FoMi");
TweakItem("Base.MeatSteamBun","DisplayCategory","FoMi");
TweakItem("Base.Maki","DisplayCategory","FoMi");
TweakItem("Base.Macandcheese","DisplayCategory","FoMi");
TweakItem("Base.Lollipop","DisplayCategory","FoMi");
TweakItem("Base.Icecream","DisplayCategory","FoMi");
TweakItem("Base.Hotdog","DisplayCategory","FoMi");
TweakItem("Base.Honey","DisplayCategory","FoMi");
TweakItem("Base.Fries","DisplayCategory","FoMi");
TweakItem("Base.DoughnutChocolate","DisplayCategory","FoMi");
TweakItem("Base.DoughnutFrosted","DisplayCategory","FoMi");
TweakItem("Base.DoughnutJelly","DisplayCategory","FoMi");
TweakItem("Base.DoughnutPlain","DisplayCategory","FoMi");
TweakItem("Base.Cupcake","DisplayCategory","FoMi");
TweakItem("Base.Crisps","DisplayCategory","FoMi");
TweakItem("Base.Crisps2","DisplayCategory","FoMi");
TweakItem("Base.Crisps3","DisplayCategory","FoMi");
TweakItem("Base.Crisps4","DisplayCategory","FoMi");
TweakItem("Base.Corndog","DisplayCategory","FoMi");
TweakItem("Base.CookiesChocolate","DisplayCategory","FoMi");
TweakItem("Base.CookiesOatmeal","DisplayCategory","FoMi");
TweakItem("Base.CookiesShortbread","DisplayCategory","FoMi");
TweakItem("Base.CookieChocolateChip","DisplayCategory","FoMi");
TweakItem("Base.CookieJelly","DisplayCategory","FoMi");
TweakItem("Base.Coffee2","DisplayCategory","FoMi");
TweakItem("Base.Chocolate","DisplayCategory","FoMi");
TweakItem("Base.ChickenFried","DisplayCategory","FoMi");
TweakItem("Base.CheeseSandwich","DisplayCategory","FoMi");
TweakItem("Base.Cheese","DisplayCategory","FoMi");
TweakItem("Base.Cereal","DisplayCategory","FoMi");
TweakItem("Base.Candycane","DisplayCategory","FoMi");
TweakItem("Base.CakeCarrot","DisplayCategory","FoMi");
TweakItem("Base.CakeCheeseCake","DisplayCategory","FoMi");
TweakItem("Base.CakeChocolate","DisplayCategory","FoMi");
TweakItem("Base.CakeRedVelvet","DisplayCategory","FoMi");
TweakItem("Base.CakeStrawberryShortcake","DisplayCategory","FoMi");
TweakItem("Base.CakeBlackForest","DisplayCategory","FoMi");
TweakItem("Base.Burger","DisplayCategory","FoMi");
TweakItem("Base.Butter","DisplayCategory","FoMi");
TweakItem("Base.BagelPlain","DisplayCategory","FoMi");
TweakItem("Base.BagelPoppy","DisplayCategory","FoMi");
TweakItem("Base.BagelSesame","DisplayCategory","FoMi");

--Vegetable
TweakItem("Base.Zucchini","DisplayCategory","FoVe");
TweakItem("farming.Tomato","DisplayCategory","FoVe");
TweakItem("farming.Potato","DisplayCategory","FoVe");
TweakItem("farming.RedRadish","DisplayCategory","FoVe");
TweakItem("Base.Pickles","DisplayCategory","FoVe");
TweakItem("Base.Peas","DisplayCategory","FoVe");
TweakItem("Base.Leek","DisplayCategory","FoVe");
TweakItem("Base.Lettuce","DisplayCategory","FoVe");
TweakItem("Base.MushroomGeneric1","DisplayCategory","FoVe");
TweakItem("Base.MushroomGeneric2","DisplayCategory","FoVe");
TweakItem("Base.MushroomGeneric3","DisplayCategory","FoVe");
TweakItem("Base.MushroomGeneric4","DisplayCategory","FoVe");
TweakItem("Base.MushroomGeneric5","DisplayCategory","FoVe");
TweakItem("Base.MushroomGeneric6","DisplayCategory","FoVe");
TweakItem("Base.MushroomGeneric7","DisplayCategory","FoVe");
TweakItem("Base.Onion","DisplayCategory","FoVe");
TweakItem("Base.Eggplant","DisplayCategory","FoVe");
TweakItem("Base.Carrots","DisplayCategory","FoVe");
TweakItem("Base.Corn","DisplayCategory","FoVe");
TweakItem("farming.Cabbage","DisplayCategory","FoVe");
TweakItem("Base.Avocado","DisplayCategory","FoVe");
TweakItem("Base.BellPepper","DisplayCategory","FoVe");
TweakItem("Base.Broccoli","DisplayCategory","FoVe");
