if getActivatedMods():contains("ItemTweakerAPI") then
require("ItemTweaker_Core");
else return end

--Literature
--Leisure
TweakItem("Base.Book","DisplayCategory","LiLe");
TweakItem("Base.ComicBook","DisplayCategory","LiLe");
TweakItem("Base.HottieZ","DisplayCategory","LiLe");
TweakItem("Base.Magazine","DisplayCategory","LiLe");
TweakItem("Base.Newspaper","DisplayCategory","LiLe");

--Map
TweakItem("Base.MarchRidgeMap","DisplayCategory","LiMa");
TweakItem("Base.MuldraughMap","DisplayCategory","LiMa");
TweakItem("Base.RiversideMap","DisplayCategory","LiMa");
TweakItem("Base.RosewoodMap","DisplayCategory","LiMa");
TweakItem("Base.WestpointMap","DisplayCategory","LiMa");

--Writable
TweakItem("Base.Journal","DisplayCategory","LiWr");
TweakItem("Base.Notebook","DisplayCategory","LiWr");
TweakItem("Base.SheetPaper2","DisplayCategory","LiWr");

--Skill Book
TweakItem("Base.BookCarpentry1","DisplayCategory","LiSb");
TweakItem("Base.BookCarpentry2","DisplayCategory","LiSb");
TweakItem("Base.BookCarpentry3","DisplayCategory","LiSb");
TweakItem("Base.BookCarpentry4","DisplayCategory","LiSb");
TweakItem("Base.BookCarpentry5","DisplayCategory","LiSb");
TweakItem("Base.BookCooking1","DisplayCategory","LiSb");
TweakItem("Base.BookCooking2","DisplayCategory","LiSb");
TweakItem("Base.BookCooking3","DisplayCategory","LiSb");
TweakItem("Base.BookCooking4","DisplayCategory","LiSb");
TweakItem("Base.BookCooking5","DisplayCategory","LiSb");
TweakItem("Base.BookElectrician1","DisplayCategory","LiSb");
TweakItem("Base.BookElectrician2","DisplayCategory","LiSb");
TweakItem("Base.BookElectrician3","DisplayCategory","LiSb");
TweakItem("Base.BookElectrician4","DisplayCategory","LiSb");
TweakItem("Base.BookElectrician5","DisplayCategory","LiSb");
TweakItem("Base.BookFarming1","DisplayCategory","LiSb");
TweakItem("Base.BookFarming2","DisplayCategory","LiSb");
TweakItem("Base.BookFarming3","DisplayCategory","LiSb");
TweakItem("Base.BookFarming4","DisplayCategory","LiSb");
TweakItem("Base.BookFarming5","DisplayCategory","LiSb");
TweakItem("Base.BookFirstAid1","DisplayCategory","LiSb");
TweakItem("Base.BookFirstAid2","DisplayCategory","LiSb");
TweakItem("Base.BookFirstAid3","DisplayCategory","LiSb");
TweakItem("Base.BookFirstAid4","DisplayCategory","LiSb");
TweakItem("Base.BookFirstAid5","DisplayCategory","LiSb");
TweakItem("Base.BookFishing1","DisplayCategory","LiSb");
TweakItem("Base.BookFishing2","DisplayCategory","LiSb");
TweakItem("Base.BookFishing3","DisplayCategory","LiSb");
TweakItem("Base.BookFishing4","DisplayCategory","LiSb");
TweakItem("Base.BookFishing5","DisplayCategory","LiSb");
TweakItem("Base.BookForaging1","DisplayCategory","LiSb");
TweakItem("Base.BookForaging2","DisplayCategory","LiSb");
TweakItem("Base.BookForaging3","DisplayCategory","LiSb");
TweakItem("Base.BookForaging4","DisplayCategory","LiSb");
TweakItem("Base.BookForaging5","DisplayCategory","LiSb");
TweakItem("Base.BookMechanic1","DisplayCategory","LiSb");
TweakItem("Base.BookMechanic2","DisplayCategory","LiSb");
TweakItem("Base.BookMechanic3","DisplayCategory","LiSb");
TweakItem("Base.BookMechanic4","DisplayCategory","LiSb");
TweakItem("Base.BookMechanic5","DisplayCategory","LiSb");
TweakItem("Base.BookMetalWelding1","DisplayCategory","LiSb");
TweakItem("Base.BookMetalWelding2","DisplayCategory","LiSb");
TweakItem("Base.BookMetalWelding3","DisplayCategory","LiSb");
TweakItem("Base.BookMetalWelding4","DisplayCategory","LiSb");
TweakItem("Base.BookMetalWelding5","DisplayCategory","LiSb");
TweakItem("Base.BookTailoring1","DisplayCategory","LiSb");
TweakItem("Base.BookTailoring2","DisplayCategory","LiSb");
TweakItem("Base.BookTailoring3","DisplayCategory","LiSb");
TweakItem("Base.BookTailoring4","DisplayCategory","LiSb");
TweakItem("Base.BookTailoring5","DisplayCategory","LiSb");
TweakItem("Base.BookTrapping1","DisplayCategory","LiSb");
TweakItem("Base.BookTrapping2","DisplayCategory","LiSb");
TweakItem("Base.BookTrapping3","DisplayCategory","LiSb");
TweakItem("Base.BookTrapping4","DisplayCategory","LiSb");
TweakItem("Base.BookTrapping5","DisplayCategory","LiSb");

--Recipe Magazine
TweakItem("Base.CookingMag1","DisplayCategory","LiRm");
TweakItem("Base.CookingMag2","DisplayCategory","LiRm");
TweakItem("Base.ElectronicsMag1","DisplayCategory","LiRm");
TweakItem("Base.ElectronicsMag2","DisplayCategory","LiRm");
TweakItem("Base.ElectronicsMag3","DisplayCategory","LiRm");
TweakItem("Base.ElectronicsMag4","DisplayCategory","LiRm");
TweakItem("Base.ElectronicsMag5","DisplayCategory","LiRm");
TweakItem("Base.EngineerMagazine1","DisplayCategory","LiRm");
TweakItem("Base.EngineerMagazine2","DisplayCategory","LiRm");
TweakItem("Base.FarmingMag1","DisplayCategory","LiRm");
TweakItem("Base.FishingMag1","DisplayCategory","LiRm");
TweakItem("Base.FishingMag2","DisplayCategory","LiRm");
TweakItem("Radio.RadioMag1","DisplayCategory","LiRm");
TweakItem("Radio.RadioMag2","DisplayCategory","LiRm");
TweakItem("Radio.RadioMag3","DisplayCategory","LiRm");
TweakItem("Base.HerbalistMag","DisplayCategory","LiRm");
TweakItem("Base.HuntingMag1","DisplayCategory","LiRm");
TweakItem("Base.HuntingMag2","DisplayCategory","LiRm");
TweakItem("Base.HuntingMag3","DisplayCategory","LiRm");
TweakItem("Base.MechanicMag1","DisplayCategory","LiRm");
TweakItem("Base.MechanicMag2","DisplayCategory","LiRm");
TweakItem("Base.MechanicMag3","DisplayCategory","LiRm");
TweakItem("Base.MetalworkMag1","DisplayCategory","LiRm");
TweakItem("Base.MetalworkMag2","DisplayCategory","LiRm");
TweakItem("Base.MetalworkMag3","DisplayCategory","LiRm");
TweakItem("Base.MetalworkMag4","DisplayCategory","LiRm");
