if getActivatedMods():contains("ItemTweakerAPI") then
require("ItemTweaker_Core");
else return end

--Miscellaneous
TweakItem("Base.Baseball","DisplayCategory","Mi");
TweakItem("Base.Basketball","DisplayCategory","Mi");
TweakItem("Base.Bell","DisplayCategory","Mi");
TweakItem("Base.Bricktoys","DisplayCategory","Mi");
TweakItem("Base.Button","DisplayCategory","Mi");
TweakItem("Base.CatToy","DisplayCategory","Mi");
TweakItem("Base.ChessBlack","DisplayCategory","Mi");
TweakItem("Base.ChessWhite","DisplayCategory","Mi");
TweakItem("Base.Cologne","DisplayCategory","Mi");
TweakItem("Base.Comb","DisplayCategory","Mi");
TweakItem("Base.Corkscrew","DisplayCategory","Mi");
TweakItem("Base.Crayons","DisplayCategory","Mi");
TweakItem("Base.CreditCard","DisplayCategory","Mi");
TweakItem("Base.Cube","DisplayCategory","Mi");
TweakItem("Base.Dart","DisplayCategory","Mi");
TweakItem("Base.Disc","DisplayCategory","Mi");
TweakItem("Base.DogChew","DisplayCategory","Mi");
TweakItem("Base.Doll","DisplayCategory","Mi");
TweakItem("Base.Football","DisplayCategory","Mi");
TweakItem("Base.Frame","DisplayCategory","Mi");
TweakItem("Base.GolfBall","DisplayCategory","Mi");
TweakItem("Base.KnittingNeedles","DisplayCategory","Mi");
TweakItem("Base.Lamp","DisplayCategory","Mi");
TweakItem("Base.Lipstick","DisplayCategory","Mi");
TweakItem("Base.Mirror","DisplayCategory","Mi");
TweakItem("Base.Money","DisplayCategory","Mi");
TweakItem("Base.Perfume","DisplayCategory","Mi");
TweakItem("Base.PoolBall","DisplayCategory","Mi");
TweakItem("Base.Razor","DisplayCategory","Mi");
TweakItem("Base.RubberBand","DisplayCategory","Mi");
TweakItem("Base.Rubberducky","DisplayCategory","Mi");
TweakItem("Base.Spiffo","DisplayCategory","Mi");
TweakItem("Base.Sponge","DisplayCategory","Mi");
TweakItem("Base.TennisBall","DisplayCategory","Mi");
TweakItem("Base.Toothbrush","DisplayCategory","Mi");
TweakItem("Base.Toothpaste","DisplayCategory","Mi");
TweakItem("Base.ToyBear","DisplayCategory","Mi");
TweakItem("Base.ToyCar","DisplayCategory","Mi");
TweakItem("Base.Wallet","DisplayCategory","Mi");
TweakItem("Base.Wallet2","DisplayCategory","Mi");
TweakItem("Base.Wallet3","DisplayCategory","Mi");
TweakItem("Base.Wallet4","DisplayCategory","Mi");
TweakItem("Base.Yoyo","DisplayCategory","Mi");
